name: Python

on:
  push:
    branches: [main]

  pull_request:
  merge_group:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/python-test.yaml

  lint:
    name: Lint
    uses: ./.github/workflows/python-lint.yaml
